import type { ServiceSlug } from "./content";

export type PortfolioProject = {
  slug: string;
  service: ServiceSlug;
  /** ISO date — drives both display and freshness signal for SEO. */
  date: string;
  /** Controls the masonry rhythm — tall/wide/square proportions. */
  ratio: "portrait" | "square" | "landscape";
  /** Cover image shown in grids. */
  photo: string;
  /** Full set for the project, cover first — powers the lightbox. */
  photos: string[];
};

export const portfolioProjects: PortfolioProject[] = [
  {
    slug: "harbour-medical-wrap",
    service: "building-cladding",
    date: "2026-08-16",
    ratio: "portrait",
    photo: "/photos/portfolio/building-cladding/harbour-medical-wrap/01.jpg",
    photos: ["/photos/portfolio/building-cladding/harbour-medical-wrap/01.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/02.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/03.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/04.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/05.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/06.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/07.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/08.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/09.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/10.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/11.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/12.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/13.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/14.jpg","/photos/portfolio/building-cladding/harbour-medical-wrap/15.jpg"],
  },
  {
    slug: "kindergarten-wall-decals",
    service: "building-cladding",
    date: "2026-08-13",
    ratio: "portrait",
    photo: "/photos/portfolio/building-cladding/kindergarten-wall-decals/01.jpg",
    photos: ["/photos/portfolio/building-cladding/kindergarten-wall-decals/01.jpg","/photos/portfolio/building-cladding/kindergarten-wall-decals/02.jpg","/photos/portfolio/building-cladding/kindergarten-wall-decals/03.jpg","/photos/portfolio/building-cladding/kindergarten-wall-decals/04.jpg","/photos/portfolio/building-cladding/kindergarten-wall-decals/05.jpg","/photos/portfolio/building-cladding/kindergarten-wall-decals/06.jpg","/photos/portfolio/building-cladding/kindergarten-wall-decals/07.jpg","/photos/portfolio/building-cladding/kindergarten-wall-decals/08.jpg"],
  },
  {
    slug: "kiosk-roof-structure",
    service: "building-cladding",
    date: "2026-08-10",
    ratio: "portrait",
    photo: "/photos/portfolio/building-cladding/kiosk-roof-structure/01.jpg",
    photos: ["/photos/portfolio/building-cladding/kiosk-roof-structure/01.jpg"],
  },
  {
    slug: "polycarpou-keo-wall-wrap",
    service: "building-cladding",
    date: "2026-08-07",
    ratio: "landscape",
    photo: "/photos/portfolio/building-cladding/polycarpou-keo-wall-wrap/01.jpg",
    photos: ["/photos/portfolio/building-cladding/polycarpou-keo-wall-wrap/01.jpg","/photos/portfolio/building-cladding/polycarpou-keo-wall-wrap/02.jpg","/photos/portfolio/building-cladding/polycarpou-keo-wall-wrap/03.jpg","/photos/portfolio/building-cladding/polycarpou-keo-wall-wrap/04.jpg","/photos/portfolio/building-cladding/polycarpou-keo-wall-wrap/05.jpg","/photos/portfolio/building-cladding/polycarpou-keo-wall-wrap/06.jpg","/photos/portfolio/building-cladding/polycarpou-keo-wall-wrap/07.jpg","/photos/portfolio/building-cladding/polycarpou-keo-wall-wrap/08.jpg"],
  },
  {
    slug: "artio-stone-carving",
    service: "engraving-cutting",
    date: "2026-08-04",
    ratio: "portrait",
    photo: "/photos/portfolio/engraving-cutting/artio-stone-carving/01.jpg",
    photos: ["/photos/portfolio/engraving-cutting/artio-stone-carving/01.jpg","/photos/portfolio/engraving-cutting/artio-stone-carving/02.jpg","/photos/portfolio/engraving-cutting/artio-stone-carving/03.jpg","/photos/portfolio/engraving-cutting/artio-stone-carving/04.jpg"],
  },
  {
    slug: "bronze-engraved-plaques",
    service: "engraving-cutting",
    date: "2026-08-01",
    ratio: "portrait",
    photo: "/photos/portfolio/engraving-cutting/bronze-engraved-plaques/01.jpg",
    photos: ["/photos/portfolio/engraving-cutting/bronze-engraved-plaques/01.jpg","/photos/portfolio/engraving-cutting/bronze-engraved-plaques/02.jpg","/photos/portfolio/engraving-cutting/bronze-engraved-plaques/03.jpg","/photos/portfolio/engraving-cutting/bronze-engraved-plaques/04.jpg"],
  },
  {
    slug: "ceiling-led-panels",
    service: "engraving-cutting",
    date: "2026-07-29",
    ratio: "portrait",
    photo: "/photos/portfolio/engraving-cutting/ceiling-led-panels/01.jpg",
    photos: ["/photos/portfolio/engraving-cutting/ceiling-led-panels/01.jpg","/photos/portfolio/engraving-cutting/ceiling-led-panels/02.jpg"],
  },
  {
    slug: "fabricated-letters-pink",
    service: "engraving-cutting",
    date: "2026-07-26",
    ratio: "portrait",
    photo: "/photos/portfolio/engraving-cutting/fabricated-letters-pink/01.jpg",
    photos: ["/photos/portfolio/engraving-cutting/fabricated-letters-pink/01.jpg","/photos/portfolio/engraving-cutting/fabricated-letters-pink/02.jpg"],
  },
  {
    slug: "fabricated-letters-workbench",
    service: "engraving-cutting",
    date: "2026-07-23",
    ratio: "portrait",
    photo: "/photos/portfolio/engraving-cutting/fabricated-letters-workbench/01.jpg",
    photos: ["/photos/portfolio/engraving-cutting/fabricated-letters-workbench/01.jpg"],
  },
  {
    slug: "led-channel-letters",
    service: "engraving-cutting",
    date: "2026-07-20",
    ratio: "portrait",
    photo: "/photos/portfolio/engraving-cutting/led-channel-letters/01.jpg",
    photos: ["/photos/portfolio/engraving-cutting/led-channel-letters/01.jpg","/photos/portfolio/engraving-cutting/led-channel-letters/02.jpg","/photos/portfolio/engraving-cutting/led-channel-letters/03.jpg"],
  },
  {
    slug: "led-ring-fixture",
    service: "engraving-cutting",
    date: "2026-07-17",
    ratio: "portrait",
    photo: "/photos/portfolio/engraving-cutting/led-ring-fixture/01.jpg",
    photos: ["/photos/portfolio/engraving-cutting/led-ring-fixture/01.jpg"],
  },
  {
    slug: "metal-letter-e",
    service: "engraving-cutting",
    date: "2026-07-14",
    ratio: "portrait",
    photo: "/photos/portfolio/engraving-cutting/metal-letter-e/01.jpg",
    photos: ["/photos/portfolio/engraving-cutting/metal-letter-e/01.jpg"],
  },
  {
    slug: "red-plastic-cutout",
    service: "engraving-cutting",
    date: "2026-07-11",
    ratio: "portrait",
    photo: "/photos/portfolio/engraving-cutting/red-plastic-cutout/01.jpg",
    photos: ["/photos/portfolio/engraving-cutting/red-plastic-cutout/01.jpg"],
  },
  {
    slug: "floor-graphic-decal",
    service: "print-vinyl",
    date: "2026-07-08",
    ratio: "portrait",
    photo: "/photos/portfolio/print-vinyl/floor-graphic-decal/01.jpg",
    photos: ["/photos/portfolio/print-vinyl/floor-graphic-decal/01.jpg"],
  },
  {
    slug: "art-fashion-rollup",
    service: "promotional-events",
    date: "2026-07-05",
    ratio: "portrait",
    photo: "/photos/portfolio/promotional-events/art-fashion-rollup/01.jpg",
    photos: ["/photos/portfolio/promotional-events/art-fashion-rollup/01.jpg"],
  },
  {
    slug: "event-backdrop-ballroom",
    service: "promotional-events",
    date: "2026-07-02",
    ratio: "portrait",
    photo: "/photos/portfolio/promotional-events/event-backdrop-ballroom/01.jpg",
    photos: ["/photos/portfolio/promotional-events/event-backdrop-ballroom/01.jpg","/photos/portfolio/promotional-events/event-backdrop-ballroom/02.jpg"],
  },
  {
    slug: "flag-banner",
    service: "promotional-events",
    date: "2026-06-29",
    ratio: "portrait",
    photo: "/photos/portfolio/promotional-events/flag-banner/01.jpg",
    photos: ["/photos/portfolio/promotional-events/flag-banner/01.jpg"],
  },
  {
    slug: "greekby-rollup",
    service: "promotional-events",
    date: "2026-06-26",
    ratio: "portrait",
    photo: "/photos/portfolio/promotional-events/greekby-rollup/01.jpg",
    photos: ["/photos/portfolio/promotional-events/greekby-rollup/01.jpg"],
  },
  {
    slug: "research-rollup",
    service: "promotional-events",
    date: "2026-06-23",
    ratio: "portrait",
    photo: "/photos/portfolio/promotional-events/research-rollup/01.jpg",
    photos: ["/photos/portfolio/promotional-events/research-rollup/01.jpg"],
  },
  {
    slug: "24-royal",
    service: "signage",
    date: "2026-06-20",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/24-royal/01.jpg",
    photos: ["/photos/portfolio/signage/24-royal/01.jpg"],
  },
  {
    slug: "barzilay-oregon-realty-signs",
    service: "signage",
    date: "2026-06-17",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/barzilay-oregon-realty-signs/01.jpg",
    photos: ["/photos/portfolio/signage/barzilay-oregon-realty-signs/01.jpg"],
  },
  {
    slug: "be-on",
    service: "signage",
    date: "2026-06-14",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/be-on/01.jpg",
    photos: ["/photos/portfolio/signage/be-on/01.jpg"],
  },
  {
    slug: "beach-bar-kiosk",
    service: "signage",
    date: "2026-06-11",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/beach-bar-kiosk/01.jpg",
    photos: ["/photos/portfolio/signage/beach-bar-kiosk/01.jpg","/photos/portfolio/signage/beach-bar-kiosk/02.jpg"],
  },
  {
    slug: "bepanta",
    service: "signage",
    date: "2026-06-08",
    ratio: "square",
    photo: "/photos/portfolio/signage/bepanta/01.jpg",
    photos: ["/photos/portfolio/signage/bepanta/01.jpg","/photos/portfolio/signage/bepanta/02.jpg","/photos/portfolio/signage/bepanta/03.jpg","/photos/portfolio/signage/bepanta/04.jpg"],
  },
  {
    slug: "best-seal-badge",
    service: "signage",
    date: "2026-06-05",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/best-seal-badge/01.jpg",
    photos: ["/photos/portfolio/signage/best-seal-badge/01.jpg"],
  },
  {
    slug: "billboard-land-banner",
    service: "signage",
    date: "2026-06-02",
    ratio: "landscape",
    photo: "/photos/portfolio/signage/billboard-land-banner/01.jpg",
    photos: ["/photos/portfolio/signage/billboard-land-banner/01.jpg"],
  },
  {
    slug: "bloom",
    service: "signage",
    date: "2026-05-30",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/bloom/01.jpg",
    photos: ["/photos/portfolio/signage/bloom/01.jpg","/photos/portfolio/signage/bloom/02.jpg"],
  },
  {
    slug: "blue-archway-entrance",
    service: "signage",
    date: "2026-05-27",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/blue-archway-entrance/01.jpg",
    photos: ["/photos/portfolio/signage/blue-archway-entrance/01.jpg"],
  },
  {
    slug: "building-address-plaque",
    service: "signage",
    date: "2026-05-24",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/building-address-plaque/01.jpg",
    photos: ["/photos/portfolio/signage/building-address-plaque/01.jpg"],
  },
  {
    slug: "building-for-rent",
    service: "signage",
    date: "2026-05-21",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/building-for-rent/01.jpg",
    photos: ["/photos/portfolio/signage/building-for-rent/01.jpg","/photos/portfolio/signage/building-for-rent/02.jpg"],
  },
  {
    slug: "by-velcheva-boutique",
    service: "signage",
    date: "2026-05-18",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/by-velcheva-boutique/01.jpg",
    photos: ["/photos/portfolio/signage/by-velcheva-boutique/01.jpg","/photos/portfolio/signage/by-velcheva-boutique/02.jpg","/photos/portfolio/signage/by-velcheva-boutique/03.jpg","/photos/portfolio/signage/by-velcheva-boutique/04.jpg","/photos/portfolio/signage/by-velcheva-boutique/05.jpg","/photos/portfolio/signage/by-velcheva-boutique/06.jpg","/photos/portfolio/signage/by-velcheva-boutique/07.jpg","/photos/portfolio/signage/by-velcheva-boutique/08.jpg"],
  },
  {
    slug: "c-cafe",
    service: "signage",
    date: "2026-05-15",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/c-cafe/01.jpg",
    photos: ["/photos/portfolio/signage/c-cafe/01.jpg"],
  },
  {
    slug: "calzature",
    service: "signage",
    date: "2026-05-12",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/calzature/01.jpg",
    photos: ["/photos/portfolio/signage/calzature/01.jpg","/photos/portfolio/signage/calzature/02.jpg","/photos/portfolio/signage/calzature/03.jpg","/photos/portfolio/signage/calzature/04.jpg"],
  },
  {
    slug: "cat-health-clinic",
    service: "signage",
    date: "2026-05-09",
    ratio: "landscape",
    photo: "/photos/portfolio/signage/cat-health-clinic/01.jpg",
    photos: ["/photos/portfolio/signage/cat-health-clinic/01.jpg","/photos/portfolio/signage/cat-health-clinic/02.jpg"],
  },
  {
    slug: "construction-hoarding",
    service: "signage",
    date: "2026-05-06",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/construction-hoarding/01.jpg",
    photos: ["/photos/portfolio/signage/construction-hoarding/01.jpg"],
  },
  {
    slug: "crocs-coming-soon",
    service: "signage",
    date: "2026-05-03",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/crocs-coming-soon/01.jpg",
    photos: ["/photos/portfolio/signage/crocs-coming-soon/01.jpg"],
  },
  {
    slug: "cube-cyta",
    service: "signage",
    date: "2026-04-30",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/cube-cyta/01.jpg",
    photos: ["/photos/portfolio/signage/cube-cyta/01.jpg","/photos/portfolio/signage/cube-cyta/02.jpg","/photos/portfolio/signage/cube-cyta/03.jpg"],
  },
  {
    slug: "dental-clinic-fkiara",
    service: "signage",
    date: "2026-04-27",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/dental-clinic-fkiara/01.jpg",
    photos: ["/photos/portfolio/signage/dental-clinic-fkiara/01.jpg","/photos/portfolio/signage/dental-clinic-fkiara/02.jpg"],
  },
  {
    slug: "discount-stores",
    service: "signage",
    date: "2026-04-24",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/discount-stores/01.jpg",
    photos: ["/photos/portfolio/signage/discount-stores/01.jpg"],
  },
  {
    slug: "elicious-burger-house",
    service: "signage",
    date: "2026-04-21",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/elicious-burger-house/01.jpg",
    photos: ["/photos/portfolio/signage/elicious-burger-house/01.jpg","/photos/portfolio/signage/elicious-burger-house/02.jpg","/photos/portfolio/signage/elicious-burger-house/03.jpg","/photos/portfolio/signage/elicious-burger-house/04.jpg","/photos/portfolio/signage/elicious-burger-house/05.jpg","/photos/portfolio/signage/elicious-burger-house/06.jpg"],
  },
  {
    slug: "elinn-hotel",
    service: "signage",
    date: "2026-04-18",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/elinn-hotel/01.jpg",
    photos: ["/photos/portfolio/signage/elinn-hotel/01.jpg","/photos/portfolio/signage/elinn-hotel/02.jpg","/photos/portfolio/signage/elinn-hotel/03.jpg","/photos/portfolio/signage/elinn-hotel/04.jpg"],
  },
  {
    slug: "ergofoto",
    service: "signage",
    date: "2026-04-15",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/ergofoto/01.jpg",
    photos: ["/photos/portfolio/signage/ergofoto/01.jpg","/photos/portfolio/signage/ergofoto/02.jpg"],
  },
  {
    slug: "eye-contact",
    service: "signage",
    date: "2026-04-12",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/eye-contact/01.jpg",
    photos: ["/photos/portfolio/signage/eye-contact/01.jpg","/photos/portfolio/signage/eye-contact/02.jpg","/photos/portfolio/signage/eye-contact/03.jpg","/photos/portfolio/signage/eye-contact/04.jpg"],
  },
  {
    slug: "for-sale-signs",
    service: "signage",
    date: "2026-04-09",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/for-sale-signs/01.jpg",
    photos: ["/photos/portfolio/signage/for-sale-signs/01.jpg","/photos/portfolio/signage/for-sale-signs/02.jpg"],
  },
  {
    slug: "gym-wall-decal",
    service: "signage",
    date: "2026-04-06",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/gym-wall-decal/01.jpg",
    photos: ["/photos/portfolio/signage/gym-wall-decal/01.jpg"],
  },
  {
    slug: "harbour-medical-branch",
    service: "signage",
    date: "2026-04-03",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/harbour-medical-branch/01.jpg",
    photos: ["/photos/portfolio/signage/harbour-medical-branch/01.jpg"],
  },
  {
    slug: "husqvarna-kyprianou",
    service: "signage",
    date: "2026-03-31",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/husqvarna-kyprianou/01.jpg",
    photos: ["/photos/portfolio/signage/husqvarna-kyprianou/01.jpg","/photos/portfolio/signage/husqvarna-kyprianou/02.jpg"],
  },
  {
    slug: "k-barber-shop",
    service: "signage",
    date: "2026-03-28",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/k-barber-shop/01.jpg",
    photos: ["/photos/portfolio/signage/k-barber-shop/01.jpg"],
  },
  {
    slug: "kaiser-stihl-dealer",
    service: "signage",
    date: "2026-03-25",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/kaiser-stihl-dealer/01.jpg",
    photos: ["/photos/portfolio/signage/kaiser-stihl-dealer/01.jpg","/photos/portfolio/signage/kaiser-stihl-dealer/02.jpg"],
  },
  {
    slug: "ladore",
    service: "signage",
    date: "2026-03-22",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/ladore/01.jpg",
    photos: ["/photos/portfolio/signage/ladore/01.jpg","/photos/portfolio/signage/ladore/02.jpg","/photos/portfolio/signage/ladore/03.jpg"],
  },
  {
    slug: "limassol-municipality",
    service: "signage",
    date: "2026-03-19",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/limassol-municipality/01.jpg",
    photos: ["/photos/portfolio/signage/limassol-municipality/01.jpg","/photos/portfolio/signage/limassol-municipality/02.jpg"],
  },
  {
    slug: "master-loncin-kaiser-panels",
    service: "signage",
    date: "2026-03-16",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/master-loncin-kaiser-panels/01.jpg",
    photos: ["/photos/portfolio/signage/master-loncin-kaiser-panels/01.jpg","/photos/portfolio/signage/master-loncin-kaiser-panels/02.jpg"],
  },
  {
    slug: "medical-center-entrance",
    service: "signage",
    date: "2026-03-13",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/medical-center-entrance/01.jpg",
    photos: ["/photos/portfolio/signage/medical-center-entrance/01.jpg","/photos/portfolio/signage/medical-center-entrance/02.jpg","/photos/portfolio/signage/medical-center-entrance/03.jpg"],
  },
  {
    slug: "medical-directory-plaques",
    service: "signage",
    date: "2026-03-10",
    ratio: "square",
    photo: "/photos/portfolio/signage/medical-directory-plaques/01.jpg",
    photos: ["/photos/portfolio/signage/medical-directory-plaques/01.jpg","/photos/portfolio/signage/medical-directory-plaques/02.jpg","/photos/portfolio/signage/medical-directory-plaques/03.jpg","/photos/portfolio/signage/medical-directory-plaques/04.jpg"],
  },
  {
    slug: "melisses-burger-house",
    service: "signage",
    date: "2026-03-07",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/melisses-burger-house/01.jpg",
    photos: ["/photos/portfolio/signage/melisses-burger-house/01.jpg"],
  },
  {
    slug: "michaelou-law-office",
    service: "signage",
    date: "2026-03-04",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/michaelou-law-office/01.jpg",
    photos: ["/photos/portfolio/signage/michaelou-law-office/01.jpg","/photos/portfolio/signage/michaelou-law-office/02.jpg","/photos/portfolio/signage/michaelou-law-office/03.jpg"],
  },
  {
    slug: "mito-developers",
    service: "signage",
    date: "2026-03-01",
    ratio: "landscape",
    photo: "/photos/portfolio/signage/mito-developers/01.jpg",
    photos: ["/photos/portfolio/signage/mito-developers/01.jpg","/photos/portfolio/signage/mito-developers/02.jpg","/photos/portfolio/signage/mito-developers/03.jpg","/photos/portfolio/signage/mito-developers/04.jpg","/photos/portfolio/signage/mito-developers/05.jpg","/photos/portfolio/signage/mito-developers/06.jpg","/photos/portfolio/signage/mito-developers/07.jpg"],
  },
  {
    slug: "mulberry-park",
    service: "signage",
    date: "2026-02-26",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/mulberry-park/01.jpg",
    photos: ["/photos/portfolio/signage/mulberry-park/01.jpg"],
  },
  {
    slug: "nails-permanent-makeup",
    service: "signage",
    date: "2026-02-23",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/nails-permanent-makeup/01.jpg",
    photos: ["/photos/portfolio/signage/nails-permanent-makeup/01.jpg"],
  },
  {
    slug: "panther-cuts-barbershop",
    service: "signage",
    date: "2026-02-20",
    ratio: "landscape",
    photo: "/photos/portfolio/signage/panther-cuts-barbershop/01.jpg",
    photos: ["/photos/portfolio/signage/panther-cuts-barbershop/01.jpg","/photos/portfolio/signage/panther-cuts-barbershop/02.jpg","/photos/portfolio/signage/panther-cuts-barbershop/03.jpg","/photos/portfolio/signage/panther-cuts-barbershop/04.jpg","/photos/portfolio/signage/panther-cuts-barbershop/05.jpg","/photos/portfolio/signage/panther-cuts-barbershop/06.jpg"],
  },
  {
    slug: "parking-sign-plates",
    service: "signage",
    date: "2026-02-17",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/parking-sign-plates/01.jpg",
    photos: ["/photos/portfolio/signage/parking-sign-plates/01.jpg","/photos/portfolio/signage/parking-sign-plates/02.jpg"],
  },
  {
    slug: "poppy-flower-boutique",
    service: "signage",
    date: "2026-02-14",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/poppy-flower-boutique/01.jpg",
    photos: ["/photos/portfolio/signage/poppy-flower-boutique/01.jpg","/photos/portfolio/signage/poppy-flower-boutique/02.jpg","/photos/portfolio/signage/poppy-flower-boutique/03.jpg","/photos/portfolio/signage/poppy-flower-boutique/04.jpg","/photos/portfolio/signage/poppy-flower-boutique/05.jpg"],
  },
  {
    slug: "poseidonio",
    service: "signage",
    date: "2026-02-11",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/poseidonio/01.jpg",
    photos: ["/photos/portfolio/signage/poseidonio/01.jpg","/photos/portfolio/signage/poseidonio/02.jpg"],
  },
  {
    slug: "pr-anything-on-wheel",
    service: "signage",
    date: "2026-02-08",
    ratio: "landscape",
    photo: "/photos/portfolio/signage/pr-anything-on-wheel/01.jpg",
    photos: ["/photos/portfolio/signage/pr-anything-on-wheel/01.jpg","/photos/portfolio/signage/pr-anything-on-wheel/02.jpg","/photos/portfolio/signage/pr-anything-on-wheel/03.jpg","/photos/portfolio/signage/pr-anything-on-wheel/04.jpg","/photos/portfolio/signage/pr-anything-on-wheel/05.jpg","/photos/portfolio/signage/pr-anything-on-wheel/06.jpg"],
  },
  {
    slug: "pylon-monument-sign",
    service: "signage",
    date: "2026-02-05",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/pylon-monument-sign/01.jpg",
    photos: ["/photos/portfolio/signage/pylon-monument-sign/01.jpg"],
  },
  {
    slug: "raftis-sunset-breeze-villas",
    service: "signage",
    date: "2026-02-02",
    ratio: "landscape",
    photo: "/photos/portfolio/signage/raftis-sunset-breeze-villas/01.jpg",
    photos: ["/photos/portfolio/signage/raftis-sunset-breeze-villas/01.jpg","/photos/portfolio/signage/raftis-sunset-breeze-villas/02.jpg"],
  },
  {
    slug: "red-elements",
    service: "signage",
    date: "2026-01-30",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/red-elements/01.jpg",
    photos: ["/photos/portfolio/signage/red-elements/01.jpg"],
  },
  {
    slug: "right-care-clinic",
    service: "signage",
    date: "2026-01-27",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/right-care-clinic/01.jpg",
    photos: ["/photos/portfolio/signage/right-care-clinic/01.jpg","/photos/portfolio/signage/right-care-clinic/02.jpg","/photos/portfolio/signage/right-care-clinic/03.jpg","/photos/portfolio/signage/right-care-clinic/04.jpg","/photos/portfolio/signage/right-care-clinic/05.jpg","/photos/portfolio/signage/right-care-clinic/06.jpg","/photos/portfolio/signage/right-care-clinic/07.jpg","/photos/portfolio/signage/right-care-clinic/08.jpg","/photos/portfolio/signage/right-care-clinic/09.jpg","/photos/portfolio/signage/right-care-clinic/10.jpg"],
  },
  {
    slug: "rimini-ristorante",
    service: "signage",
    date: "2026-01-24",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/rimini-ristorante/01.jpg",
    photos: ["/photos/portfolio/signage/rimini-ristorante/01.jpg"],
  },
  {
    slug: "rubys-restaurant-interior",
    service: "signage",
    date: "2026-01-21",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/rubys-restaurant-interior/01.jpg",
    photos: ["/photos/portfolio/signage/rubys-restaurant-interior/01.jpg","/photos/portfolio/signage/rubys-restaurant-interior/02.jpg"],
  },
  {
    slug: "sense-by-the-beach",
    service: "signage",
    date: "2026-01-18",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/sense-by-the-beach/01.jpg",
    photos: ["/photos/portfolio/signage/sense-by-the-beach/01.jpg","/photos/portfolio/signage/sense-by-the-beach/02.jpg","/photos/portfolio/signage/sense-by-the-beach/03.jpg"],
  },
  {
    slug: "speedcare-clinic",
    service: "signage",
    date: "2026-01-15",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/speedcare-clinic/01.jpg",
    photos: ["/photos/portfolio/signage/speedcare-clinic/01.jpg"],
  },
  {
    slug: "sushi-corner",
    service: "signage",
    date: "2026-01-12",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/sushi-corner/01.jpg",
    photos: ["/photos/portfolio/signage/sushi-corner/01.jpg","/photos/portfolio/signage/sushi-corner/02.jpg","/photos/portfolio/signage/sushi-corner/03.jpg"],
  },
  {
    slug: "the-social-marketing",
    service: "signage",
    date: "2026-01-09",
    ratio: "landscape",
    photo: "/photos/portfolio/signage/the-social-marketing/01.jpg",
    photos: ["/photos/portfolio/signage/the-social-marketing/01.jpg"],
  },
  {
    slug: "under-study-project",
    service: "signage",
    date: "2026-01-06",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/under-study-project/01.jpg",
    photos: ["/photos/portfolio/signage/under-study-project/01.jpg","/photos/portfolio/signage/under-study-project/02.jpg","/photos/portfolio/signage/under-study-project/03.jpg","/photos/portfolio/signage/under-study-project/04.jpg","/photos/portfolio/signage/under-study-project/05.jpg","/photos/portfolio/signage/under-study-project/06.jpg"],
  },
  {
    slug: "wall-plaque-tree-logo",
    service: "signage",
    date: "2026-01-03",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/wall-plaque-tree-logo/01.jpg",
    photos: ["/photos/portfolio/signage/wall-plaque-tree-logo/01.jpg"],
  },
  {
    slug: "waterpark-park-signage",
    service: "signage",
    date: "2025-12-31",
    ratio: "portrait",
    photo: "/photos/portfolio/signage/waterpark-park-signage/01.jpg",
    photos: ["/photos/portfolio/signage/waterpark-park-signage/01.jpg","/photos/portfolio/signage/waterpark-park-signage/02.jpg","/photos/portfolio/signage/waterpark-park-signage/03.jpg","/photos/portfolio/signage/waterpark-park-signage/04.jpg"],
  },
  {
    slug: "atrinodomi-trucks",
    service: "vehicle-graphics",
    date: "2025-12-28",
    ratio: "landscape",
    photo: "/photos/portfolio/vehicle-graphics/atrinodomi-trucks/01.jpg",
    photos: ["/photos/portfolio/vehicle-graphics/atrinodomi-trucks/01.jpg","/photos/portfolio/vehicle-graphics/atrinodomi-trucks/02.jpg"],
  },
  {
    slug: "blue-coach-bus",
    service: "vehicle-graphics",
    date: "2025-12-25",
    ratio: "portrait",
    photo: "/photos/portfolio/vehicle-graphics/blue-coach-bus/01.jpg",
    photos: ["/photos/portfolio/vehicle-graphics/blue-coach-bus/01.jpg","/photos/portfolio/vehicle-graphics/blue-coach-bus/02.jpg"],
  },
  {
    slug: "erb-cyprus-bus",
    service: "vehicle-graphics",
    date: "2025-12-22",
    ratio: "landscape",
    photo: "/photos/portfolio/vehicle-graphics/erb-cyprus-bus/01.jpg",
    photos: ["/photos/portfolio/vehicle-graphics/erb-cyprus-bus/01.jpg","/photos/portfolio/vehicle-graphics/erb-cyprus-bus/02.jpg"],
  },
  {
    slug: "food-truck-wrap",
    service: "vehicle-graphics",
    date: "2025-12-19",
    ratio: "landscape",
    photo: "/photos/portfolio/vehicle-graphics/food-truck-wrap/01.jpg",
    photos: ["/photos/portfolio/vehicle-graphics/food-truck-wrap/01.jpg","/photos/portfolio/vehicle-graphics/food-truck-wrap/02.jpg","/photos/portfolio/vehicle-graphics/food-truck-wrap/03.jpg"],
  },
  {
    slug: "scania-bus-swirl",
    service: "vehicle-graphics",
    date: "2025-12-16",
    ratio: "landscape",
    photo: "/photos/portfolio/vehicle-graphics/scania-bus-swirl/01.jpg",
    photos: ["/photos/portfolio/vehicle-graphics/scania-bus-swirl/01.jpg","/photos/portfolio/vehicle-graphics/scania-bus-swirl/02.jpg","/photos/portfolio/vehicle-graphics/scania-bus-swirl/03.jpg","/photos/portfolio/vehicle-graphics/scania-bus-swirl/04.jpg"],
  },
  {
    slug: "valkyrian-investments-truck",
    service: "vehicle-graphics",
    date: "2025-12-13",
    ratio: "landscape",
    photo: "/photos/portfolio/vehicle-graphics/valkyrian-investments-truck/01.jpg",
    photos: ["/photos/portfolio/vehicle-graphics/valkyrian-investments-truck/01.jpg","/photos/portfolio/vehicle-graphics/valkyrian-investments-truck/02.jpg","/photos/portfolio/vehicle-graphics/valkyrian-investments-truck/03.jpg"],
  },
  {
    slug: "van-curve-wrap",
    service: "vehicle-graphics",
    date: "2025-12-10",
    ratio: "landscape",
    photo: "/photos/portfolio/vehicle-graphics/van-curve-wrap/01.jpg",
    photos: ["/photos/portfolio/vehicle-graphics/van-curve-wrap/01.jpg"],
  },
  {
    slug: "waterpark-bus",
    service: "vehicle-graphics",
    date: "2025-12-07",
    ratio: "portrait",
    photo: "/photos/portfolio/vehicle-graphics/waterpark-bus/01.jpg",
    photos: ["/photos/portfolio/vehicle-graphics/waterpark-bus/01.jpg","/photos/portfolio/vehicle-graphics/waterpark-bus/02.jpg","/photos/portfolio/vehicle-graphics/waterpark-bus/03.jpg","/photos/portfolio/vehicle-graphics/waterpark-bus/04.jpg","/photos/portfolio/vehicle-graphics/waterpark-bus/05.jpg","/photos/portfolio/vehicle-graphics/waterpark-bus/06.jpg","/photos/portfolio/vehicle-graphics/waterpark-bus/07.jpg","/photos/portfolio/vehicle-graphics/waterpark-bus/08.jpg","/photos/portfolio/vehicle-graphics/waterpark-bus/09.jpg","/photos/portfolio/vehicle-graphics/waterpark-bus/10.jpg","/photos/portfolio/vehicle-graphics/waterpark-bus/11.jpg"],
  },
  {
    slug: "waterpark-car",
    service: "vehicle-graphics",
    date: "2025-12-04",
    ratio: "portrait",
    photo: "/photos/portfolio/vehicle-graphics/waterpark-car/01.jpg",
    photos: ["/photos/portfolio/vehicle-graphics/waterpark-car/01.jpg","/photos/portfolio/vehicle-graphics/waterpark-car/02.jpg","/photos/portfolio/vehicle-graphics/waterpark-car/03.jpg","/photos/portfolio/vehicle-graphics/waterpark-car/04.jpg","/photos/portfolio/vehicle-graphics/waterpark-car/05.jpg","/photos/portfolio/vehicle-graphics/waterpark-car/06.jpg","/photos/portfolio/vehicle-graphics/waterpark-car/07.jpg"],
  },
];

export const ratioClass: Record<PortfolioProject["ratio"], string> = {
  portrait: "aspect-[3/4]",
  square: "aspect-square",
  landscape: "aspect-[4/3]",
};
